/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

/**
 *
 * @author DINI
 */
import com.koneksi.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        LabelLogin = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        Register = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        LevelUser = new javax.swing.JLabel();
        User = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LabelLogin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelLogin.setText("LOGIN");
        getContentPane().add(LabelLogin);
        LabelLogin.setBounds(250, 80, 43, 26);

        Username.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Username.setText("Username");
        getContentPane().add(Username);
        Username.setBounds(100, 180, 56, 26);

        password.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        password.setText("Password");
        getContentPane().add(password);
        password.setBounds(100, 230, 56, 26);
        getContentPane().add(UserName);
        UserName.setBounds(230, 180, 240, 22);

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(230, 230, 240, 22);

        Register.setText("Register");
        getContentPane().add(Register);
        Register.setBounds(260, 320, 72, 23);

        Login.setText("Login");
        getContentPane().add(Login);
        Login.setBounds(370, 320, 72, 23);

        LevelUser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LevelUser.setText("Level User");
        getContentPane().add(LevelUser);
        LevelUser.setBounds(100, 270, 60, 17);

        User.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "- Admin ", "- Customer" }));
        getContentPane().add(User);
        User.setBounds(230, 270, 240, 22);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 560, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LevelUser;
    private javax.swing.JButton Login;
    private javax.swing.JTextField Password;
    private javax.swing.JButton Register;
    private javax.swing.JComboBox<String> User;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel Username;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel password;
    // End of variables declaration//GEN-END:variables
}
